# Generated by Django 3.1.1 on 2021-07-21 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_alter_messagemodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='sid',
            field=models.IntegerField(default=0, verbose_name='sid'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Visibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_see', models.ManyToManyField(related_name='can_see', to='auth.Group')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='auth.group')),
            ],
            options={
                'verbose_name': 'Visibility',
                'verbose_name_plural': 'Visibility',
            },
        ),
        migrations.CreateModel(
            name='ScenarioModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField(verbose_name='sid')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL, verbose_name='user2')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL, verbose_name='user1')),
            ],
        ),
        migrations.AddIndex(
            model_name='visibility',
            index=models.Index(fields=['group'], name='core_visibi_group_i_546bec_idx'),
        ),
    ]
